"""config del lector de codigo de barras

Revision ID: 94fc1932d06a
Revises: ad20fc3a9a0d
Create Date: 2026-10-01 23:55:49.744455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fc1932d06a'
down_revision = 'ad20fc3a9a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_terminador', sa.String(length=10), nullable=False, server_default='ENTER'))
        batch_op.add_column(sa.Column('scan_ms_entre_teclas', sa.Integer(), nullable=False, server_default='120'))
        batch_op.add_column(sa.Column('scan_cantidad', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('scan_prefijo_balanza', sa.String(length=5), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.drop_column('scan_prefijo_balanza')
        batch_op.drop_column('scan_cantidad')
        batch_op.drop_column('scan_ms_entre_teclas')
        batch_op.drop_column('scan_terminador')

    # ### end Alembic commands ###
