"""articulo pesable y cantidad decimal en venta

Revision ID: ad20fc3a9a0d
Revises: da505505513d
Create Date: 2026-10-01 23:49:21.480589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad20fc3a9a0d'
down_revision = 'da505505513d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_pesable', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('articulo', schema=None) as batch_op:
        batch_op.drop_column('es_pesable')

    # ### end Alembic commands ###
