"""esquema inicial Punto Kiosko

Revision ID: da505505513d
Revises: 
Create Date: 2026-10-01 22:33:32.537588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da505505513d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('precio_costo', sa.Integer(), nullable=False),
    sa.Column('margen_objetivo', sa.Integer(), nullable=True),
    sa.Column('stock_propio', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_telefono'), ['telefono'], unique=True)

    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fefo_activo', sa.Boolean(), nullable=False),
    sa.Column('vista_ventas', sa.String(length=20), nullable=False),
    sa.Column('modo_oscuro', sa.Boolean(), nullable=False),
    sa.Column('font_size', sa.String(length=20), nullable=False),
    sa.Column('impresora_termica', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('es_efectivo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_descuento', sa.Enum('PORCENTAJE', 'MONTO_FIJO', 'DOS_POR_UNO', name='tipodescuento'), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('aplicacion', sa.Enum('AUTOMATICA', 'MANUAL', name='aplicacionpromocion'), nullable=False),
    sa.Column('vigencia_desde', sa.DateTime(), nullable=False),
    sa.Column('vigencia_hasta', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('eliminada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email_personal', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'CAJERO', name='rolusuario'), nullable=False),
    sa.Column('debe_cambiar_clave', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email_personal'), ['email_personal'], unique=True)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalles', sa.JSON(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codigo_barras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('codigo_barras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_codigo_barras_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_codigo_barras_codigo'), ['codigo'], unique=True)

    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=50), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insumo_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('STOCK_BAJO', 'POR_VENCER', 'BAJO_MARGEN', name='tiponotificacion'), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('descartada', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocion_id', 'articulo_id', name='uq_promocion_producto')
    )
    with op.batch_alter_table('promocion_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocion_producto_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocion_producto_promocion_id'), ['promocion_id'], unique=False)

    op.create_table('turno_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fondo_inicial', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadoturno'), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arqueo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('efectivo_contado', sa.Integer(), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=True),
    sa.Column('diferencia', sa.Integer(), nullable=False),
    sa.Column('motivo_diferencia', sa.Text(), nullable=True),
    sa.Column('diferencia_confirmada', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turno_caja_id')
    )
    op.create_table('articulo_insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('articulo_id', 'insumo_id', name='uq_articulo_insumo')
    )
    with op.batch_alter_table('articulo_insumo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulo_insumo_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articulo_insumo_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_sistema', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_contada', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conteo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conteo_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lote_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('movimiento_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_caja_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', 'VENTA', name='tipomovimientocaja'), nullable=False),
    sa.Column('categoria', sa.Enum('PROVEEDOR', 'GASTO', 'RETIRO_DUENO', 'VUELTO', 'OTRO', name='categoriamovimientocaja'), nullable=True),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_caja', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_caja_turno_caja_id'), ['turno_caja_id'], unique=False)

    op.create_table('venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('metodo_pago_id', sa.Integer(), nullable=True),
    sa.Column('turno_caja_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('CONFIRMADA', 'ANULADA', name='estadoventa'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('descuento_promocion', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('pago_recibido', sa.Integer(), nullable=False),
    sa.Column('vuelto', sa.Integer(), nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodo_pago.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.ForeignKeyConstraint(['turno_caja_id'], ['turno_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_numero'), ['numero'], unique=False)

    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('conteo_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_caja_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('CARGA', 'AJUSTE', 'MERMA', 'SALIDA', name='tipomovimientoinventario'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['conteo_id'], ['conteo.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['movimiento_caja_id'], ['movimiento_caja.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_inventario_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_inventario_insumo_id'), ['insumo_id'], unique=False)

    op.create_table('venta_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venta_detalle_articulo_id'), ['articulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venta_detalle_venta_id'), ['venta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_detalle_venta_id'))
        batch_op.drop_index(batch_op.f('ix_venta_detalle_articulo_id'))

    op.drop_table('venta_detalle')
    with op.batch_alter_table('movimiento_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_inventario_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_inventario_articulo_id'))

    op.drop_table('movimiento_inventario')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venta_numero'))

    op.drop_table('venta')
    with op.batch_alter_table('movimiento_caja', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_caja_turno_caja_id'))

    op.drop_table('movimiento_caja')
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lote_insumo_id'))

    op.drop_table('lote')
    with op.batch_alter_table('conteo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conteo_insumo_id'))

    op.drop_table('conteo')
    with op.batch_alter_table('articulo_insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulo_insumo_insumo_id'))
        batch_op.drop_index(batch_op.f('ix_articulo_insumo_articulo_id'))

    op.drop_table('articulo_insumo')
    op.drop_table('arqueo')
    op.drop_table('turno_caja')
    with op.batch_alter_table('promocion_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocion_producto_promocion_id'))
        batch_op.drop_index(batch_op.f('ix_promocion_producto_articulo_id'))

    op.drop_table('promocion_producto')
    op.drop_table('notificacion')
    with op.batch_alter_table('insumo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insumo_proveedor_id'))

    op.drop_table('insumo')
    with op.batch_alter_table('codigo_barras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_codigo_barras_codigo'))
        batch_op.drop_index(batch_op.f('ix_codigo_barras_articulo_id'))

    op.drop_table('codigo_barras')
    op.drop_table('auditoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email_personal'))

    op.drop_table('usuario')
    op.drop_table('proveedor')
    op.drop_table('promocion')
    op.drop_table('metodo_pago')
    op.drop_table('configuracion')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_telefono'))

    op.drop_table('cliente')
    op.drop_table('articulo')
    # ### end Alembic commands ###
